driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once

client_rb:
  treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
- name: amazon-linux
  driver_config:
    box: mvbcoding/awslinux
- name: centos-6
- name: centos-7
- name: debian-8
- name: debian-9
- name: fedora-latest
- name: freebsd-10
- name: freebsd-11
- name: opensuse-leap-42
- name: ubuntu-16.04
- name: ubuntu-18.04

suites:
  - name: package
    run_list:
      - recipe[test::package]
  - name: source-1.7
    run_list:
      - recipe[test::source]
    attributes:
      haproxy:
        source_version: '1.7.8'
        source_url: 'http://www.haproxy.org/download/1.7/src/haproxy-1.7.8.tar.gz'
        source_checksum: 'ec90153ccedd20ad4015d3eaf76b502ff1f61b431d54c22b8457b5784a9ae142'
    includes: ubuntu-16.04
  - name: source-1.8
    run_list:
      - recipe[test::source]
    attributes:
      haproxy:
        source_version: '1.8.14'
        source_url: 'http://www.haproxy.org/download/1.8/src/haproxy-1.8.14.tar.gz'
        source_checksum: 'b17e402578be85e58af7a3eac99b1f675953bea9f67af2e964cf8bdbd1bd3fdf'
  - name: config_1
    run_list:
      - recipe[test::config_1]
    includes: centos-7
  - name: config_2
    run_list:
      - recipe[test::config_2]
    includes: centos-7
  - name: config_3
    run_list:
      - recipe[test::config_3]
    includes: centos-7
  - name: config_4
    run_list:
      - recipe[test::config_4]
    includes: centos-7
  - name: config_backend_search
    run_list:
      - recipe[test::config_backend_search]
    includes: centos-7
  - name: config_1_userlist
    run_list:
      - recipe[test::config_1_userlist]
    includes: centos-7
  - name: config_acl
    run_list:
      - recipe[test::config_acl]
    includes: centos-7
  - name: config_resolver
    run_list:
      - recipe[test::config_resolver]
    includes: centos-7
  - name: config_ssl_redirect
    run_list:
      - recipe[test::config_ssl_redirect]
    includes: centos-7
  - name: config_custom_template
    run_list:
      - recipe[test::config_custom_template]
    includes: centos-7
  - name: config_array
    run_list:
      - recipe[test::config_array]
    includes: centos-7
