driver:
  name: vagrant


provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: oracle-6.8
  - name: oracle-7.3
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: package
    run_list:
      - recipe[test::package]
    excludes: debian-7.11
  - name: source
    run_list:
      - recipe[test::source]
    attributes:
      haproxy:
        source_version: <%= ENV['HAPROXY_SOURCE_VERSION'].nil? ? '1.8.4' : ENV['HAPROXY_SOURCE_VERSION'] %>
        source_url: <%= ENV['HAPROXY_SOURCE_URL'].nil? ? 'http://www.haproxy.org/download/1.8/src/haproxy-1.8.4.tar.gz' : ENV['HAPROXY_SOURCE_URL'] %>
        source_checksum: <%= ENV['HAPROXY_SOURCE_CHECKSUM'].nil? ? 'e305b0a4e7dec08072841eef6ac6dcd1b5586b1eff09c2d51e152a912e8884a6' : ENV['HAPROXY_SOURCE_CHECKSUM'] %>
  - name: config_1
    run_list:
      - recipe[test::config_1]
    includes: centos-7.3
  - name: config_2
    run_list:
      - recipe[test::config_2]
    includes: centos-7.3
  - name: config_3_logs
    run_list:
      - recipe[test::config_3_logs]
    includes: centos-7.3
  - name: config_4
    run_list:
      - recipe[test::config_4]
    includes: centos-7.3
  - name: config_backend_search
    run_list:
      - recipe[test::config_backend_search]
    includes: centos-7.3
  - name: config_1_userlist
    run_list:
      - recipe[test::config_1_userlist]
    includes: centos-7.3
  - name: config_acl
    run_list:
      - recipe[test::config_acl]
    includes: centos-7.3
  - name: config_resolver
    run_list:
      - recipe[test::config_resolver]
    includes: centos-7.3
  - name: config_ssl_redirect
    run_list:
      - recipe[test::config_ssl_redirect]
    includes: centos-7.3
  - name: config_custom_template
    run_list:
      - recipe[test::config_custom_template]
    includes: centos-7.3
  - name: config_array
    run_list:
      - recipe[test::config_array]
    includes: centos-7.3
