driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once

platforms:
- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-6
  driver:
    image: dokken/centos-6
    platform: rhel
    pid_one_command: /sbin/init

- name: centos-7
  driver:
    image: dokken/centos-7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-26
  driver:
    image: dokken/fedora-26
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-27
  driver:
    image: dokken/fedora-27
    pid_one_command: /usr/lib/systemd/systemd

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd

- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init

suites:
- name: package
  run_list:
    - recipe[test::package]
- name: source
  run_list:
    - recipe[test::source]
  attributes:
    haproxy:
      source_version: <%= ENV['HAPROXY_SOURCE_VERSION'].nil? ? '1.7.8' : ENV['HAPROXY_SOURCE_VERSION'] %>
      source_url: <%= ENV['HAPROXY_SOURCE_URL'].nil? ? 'http://www.haproxy.org/download/1.7/src/haproxy-1.7.8.tar.gz' : ENV['HAPROXY_SOURCE_URL'] %>
      source_checksum: <%= ENV['HAPROXY_SOURCE_CHECKSUM'].nil? ? 'ec90153ccedd20ad4015d3eaf76b502ff1f61b431d54c22b8457b5784a9ae142' : ENV['HAPROXY_SOURCE_CHECKSUM'] %>
- name: config_1
  run_list:
    - recipe[test::config_1]
  includes: centos-7
- name: config_2
  run_list:
    - recipe[test::config_2]
  includes: centos-7
- name: config_3_logs
  run_list:
    - recipe[test::config_3_logs]
  includes: centos-7
- name: config_4
  run_list:
    - recipe[test::config_4]
  includes: centos-7
- name: config_backend_search
  run_list:
    - recipe[test::config_backend_search]
  includes: centos-7
- name: config_1_userlist
  run_list:
    - recipe[test::config_1_userlist]
  includes: centos-7
- name: config_acl
  run_list:
    - recipe[test::config_acl]
  includes: centos-7
- name: config_resolver
  run_list:
    - recipe[test::config_resolver]
  includes: centos-7
- name: config_ssl_redirect
  run_list:
    - recipe[test::config_ssl_redirect]
  includes: centos-7
- name: config_custom_template
  run_list:
    - recipe[test::config_custom_template]
  includes: centos-7
- name: config_array
  run_list:
    - recipe[test::config_array]
  includes: centos-7
