driver:
  name: vagrant


provisioner:
  name: chef_zero
  deprecations_as_errors: true

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: oracle-6.8
  - name: oracle-7.3
  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04

  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04

suites:
  - name: package
    run_list:
      - recipe[test::package]
    excludes: debian-7.11
  - name: source
    run_list:
      - recipe[test::source]
  - name: config_1
    run_list:
      - recipe[test::config_1]
    includes: centos-7.3
  - name: config_2
    run_list:
      - recipe[test::config_2]
    includes: centos-7.3
    includes: centos-7.3
  - name: config_4
    run_list:
      - recipe[test::config_4]
    includes: centos-7.3
