driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts net-tools wget

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools

- name: fedora-25
  driver:
    image: fedora:25
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which systemd-sysv initscripts wget net-tools

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: opensuse-leap
  driver:
    image: opensuse:leap
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which hostname

- name: amazon
  driver:
    image: amazonlinux:latest
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum update -y
      - RUN yum -y install which initscripts net-tools wget procps util-linux

suites:
- name: package
  run_list:
    - recipe[test::package]
- name: source
  run_list:
    - recipe[test::source]
  attributes:
    haproxy:
      source_url: <%= ENV['HAPROXY_SOURCE_URL'].nil? ? 'http://www.haproxy.org/download/1.7/src/haproxy-1.7.5.tar.gz' : ENV['HAPROXY_SOURCE_URL'] %>
      source_checksum: <%= ENV['HAPROXY_SOURCE_CHECKSUM'].nil? ? 'b04d7db6383c662eb0a421a95af7becac6d9744a1abf0df6b0280c1e61416121' : ENV['HAPROXY_SOURCE_CHECKSUM'] %>
- name: config_1
  run_list:
    - recipe[test::config_1]
  includes: centos-7
- name: config_2
  run_list:
    - recipe[test::config_2]
  includes: centos-7
- name: config_4
  run_list:
    - recipe[test::config_4]
  includes: centos-7
- name: config_backend_search
  run_list:
    - recipe[test::config_backend_search]
  includes: centos-7
- name: config_1_userlist
  run_list:
    - recipe[test::config_1_userlist]
  includes: centos-7
- name: config_acl
  run_list:
    - recipe[test::config_acl]
  includes: centos-7
- name: config_ssl_redirect
  run_list:
    - recipe[test::config_ssl_redirect]
  includes: centos-7